meta-iot-web: recipe for iotivity-node.
This commit includes the following fixes by Rijubrata Bhaumik as explained below.

I am using INSANE_SKIP_${PN} += "ldflags staticdev" to skip these QA errors
ERROR: QA Issue: No GNU_HASH in the elf binary: '/media/ssd/iot-build/tmp-glibc/work/corei7-64-ostro-linux/iotivity-node/1.0-r0/packages-split/iotivity-node/usr/lib/node_modules/iotivity/node_modules/ffi/deps/libffi/testsuite/libffi.call/a.out' [ldflags]
ERROR: QA Issue: non -staticdev package contains static .a library: iotivity-node path '/work/corei7-64-ostro-linux/iotivity-node/1.0-r0/packages-split/iotivity-node/usr/lib/node_modules/iotivity/node_modules/ffi/build/Release/obj.target/deps/libffi/libffi.a' [staticdev]
iotivity-node depends on a npm module "ffi".
If the static library libffi.a is not compiled with PIC, it cannot be used to generate the shared object.
So we have to compile with -fPIC.
Also removing the libffi (a dev package dependency) test suite right now.

iotivity-node: pass --arch=${TARGET_ARCH} to npm install.

We need to make sure that iotivity-node works on the target architecture
by passing --arch=${TARGET_ARCH} to npm install.
We can remove this once npm-install.bbclass is complete and we can
inherit from that class.

Signed-off-by: Rijubrata Bhaumik <rijubrata.bhaumik@intel.com>