nodejs: Fix FTBFS by adding missing argument to d.getVar
Observed issue (on GENIVI) is:

  ERROR: ExpansionError during parsing \
  (...)/meta-iot-web/recipes-devtools/nodejs/nodejs_6.11.0.bb
  Traceback (most recent call last):
  bb.data_smart.ExpansionError: \
  Failure expanding variable do_configure, expression was \
  export (...) \
   ./configure --prefix=/usr --without-snapshot --shared-openssl \
               --dest-cpu="${@map_nodejs_arch(d.getVar('TARGET_ARCH'), d)}" \
  (...)
  which triggered exception TypeError: \
  getVar() missing 1 required positional argument: 'expand'

Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>